services:
  - type: web
    name: quiz-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd quiz-backend && npm install
    startCommand: cd quiz-backend && node index.js
    envVars:
      - key: NODE_ENV
        value: production
